"""build_fidelity_attestations.py — PR-C0 fidelity attestation producer.

Epic #499 plan §2.7 item 9 / §2.8.5 / §5.7. Produces the three PR-C0 artifacts:

  build-coverage  the 13 renderer-generated coverage reports under
                  ``evidence/development-agent-v8/fidelity/coverage/``
  build-packet    the per-tranche reviewer packets that make the mandated
                  source-description -> discovery-summary trigger judgment
                  possible without an unaided full-text read
  build-index     the tracked signing index ``sdd/adapters/codex-skill-fidelity.yml``

Direction of trust (this is the whole point of the unit):

  * Coverage reports are MACHINE-GENERATED by the renderer
    (``skill_renderer.generate_coverage``) — plan §2.7 item 9. The independent
    closure check lives in ``check_fidelity_attestations.py``, which never
    imports that generator; this producer never imports the checker either.
  * ``build-index`` REFUSES to invent an approval. Every ``approval_binding``
    field must arrive verbatim from a real reviewer record via ``--bindings``;
    the producer only VERIFIES that the reviewer's ``reviewed_*`` digests equal
    the digests this tree actually computes. Author-filled verdicts are exactly
    what plan §2.7 forbids, so "no bindings" is an exit-2
    ``BLOCKED_PREREQUISITE``, never a default-approved index.

Candidate anchor: every digest is taken from GIT BLOB bytes at ``--rev``
(default = the PR-B merge commit that PR-P1b pinned). A Windows checkout is
CRLF under ``* text=auto``, so reading the worktree would publish digests that
Linux CI could never reproduce (plan follow-up F9). The rendered candidate
bytes are produced in memory and are deliberately NOT written into the
repository — PR-P1b Gate 1 published digests only.

Equivalent reuse (recorded per plan §3.3): the candidate render pipeline is
PR-P1b's ``run_codex_carrier_probe.build_candidate_render`` — owner PR-P1b,
interface ``(repo_root, rev, work_dir) -> CandidateRender``, pinned by
``tests/unit/test_fidelity_attestations_c0.py``. Re-implementing it here would
duplicate ~100 lines whose only correctness criterion is "produces the exact
bytes PR-P1b published".

Exit codes follow the repo-wide checker convention: 0 clean; 1 drift
(``build-coverage --check`` found a committed report that no longer matches a
fresh render); 2 unusable input / unmet prerequisite. Read-only w.r.t.
everything except its own declared output paths; no secrets; no network.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
from collections.abc import Mapping
from pathlib import Path
from typing import Any, NoReturn

import yaml

_SCRIPT_NAME = "build_fidelity_attestations.py"
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# The candidate commit PR-P1b froze and published digests for. Re-rendering on
# any other revision is a hard error, not a silent re-anchor: the published
# candidate digests are the review subject.
CANDIDATE_REV = "36f298a9995fd3b7c0dd9ad7d4f9d4fec233422f"

INDEX_RELPATH = "sdd/adapters/codex-skill-fidelity.yml"
COVERAGE_RELDIR = "evidence/development-agent-v8/fidelity/coverage"
PACKET_RELDIR = "evidence/development-agent-v8/fidelity/review-packet"
P1B_FIXTURE_RELPATH = (
    "evidence/development-agent-v8/probe/fixtures/p1b-deterministic-expected.json"
)
SOURCE_ROOT = ".claude/skills"
ARTIFACT_ROOT = ".agents/skills"
MANIFEST_RELPATH = "sdd/development-agent.yml"

INDEX_SCHEMA_VERSION = 1

# Gate 1 (2026-08-26) approved partition: 4 tranches along the HITL stage
# families, so each tranche is one coherent review sitting. Exact partition of
# the 13 translated carriers — no gap, no overlap (plan §2.8.5).
TRANCHES: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "tranche-1-flow-entry",
        (
            "mj-agent-flow-intake",
            "mj-agent-flow-repo-scan",
            "mj-agent-flow-plan",
        ),
    ),
    (
        "tranche-2-flow-build",
        (
            "mj-agent-flow-implement",
            "mj-agent-flow-verify",
            "mj-agent-flow-self-review",
        ),
    ),
    (
        "tranche-3-flow-close",
        (
            "mj-agent-flow-scope-drift",
            "mj-agent-flow-review-respond",
            "mj-agent-flow-post-merge",
        ),
    ),
    (
        "tranche-4-doc-git",
        (
            "mj-agent-doc-validate",
            "mj-agent-git-branch",
            "mj-agent-git-issue",
            "mj-agent-git-pr",
        ),
    ),
)

BINDING_KEYS = {
    "record_system", "immutable_record_id", "reviewer_identity", "verdict",
    "reviewed_candidate_commit_sha", "reviewed_source_set_sha256",
    "reviewed_artifact_set_sha256", "recorded_at",
}
VERDICTS = {"approved", "rejected"}


def _die(message: str) -> NoReturn:
    """Fail closed: stderr + exit 2, never 0 and never a bare-string SystemExit
    (which Python maps to status 1)."""
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(2)


# --------------------------------------------------------------- digest wire


def canonical_json_bytes(obj: Any) -> bytes:
    """UTF-8, no BOM, LF, 2-space indent, ensure_ascii=false, sorted keys, one
    final newline (plan §2.8.1)."""
    text = json.dumps(obj, ensure_ascii=False, indent=2, sort_keys=True)
    return (text + "\n").encode("utf-8")


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def set_digest(path_to_sha: Mapping[str, str]) -> str:
    """Plan §2.7 set-digest wire: a closed canonical JSON object
    ``path -> raw_sha256`` with code-point-sorted keys, digested over its
    canonical UTF-8 bytes. Never a directory mtime, Git tree hash or unsorted
    concatenation.

    Pinned against a published value: recomputing this over PR-P1b's
    ``candidate_output_sha256`` must reproduce its ``candidate_set_sha256``.
    """
    return sha256_hex(
        canonical_json_bytes({path: path_to_sha[path] for path in sorted(path_to_sha)})
    )


# ------------------------------------------------------------- render inputs


def _probe_module() -> Any:
    """PR-P1b's producer, imported lazily (equivalent reuse per §3.3)."""
    import scripts.sdd.run_codex_carrier_probe as probe

    return probe


def canonical_rev(repo_root: Path, rev: str) -> str:
    """Full 40-hex commit id for `rev`.

    Git resolves `36f298a` or a ref name happily, but the fixture-pin guard and
    `candidate_commit_sha` both compare/publish strings — an abbreviation of the
    CORRECT commit would otherwise be rejected as a re-anchor attempt, and a
    short sha would land in the index where the checker demands 40 hex.
    """
    probe = _probe_module()
    try:
        return probe.resolve_rev(repo_root, rev)
    except probe.GitError as exc:
        _die(f"--rev {rev!r} does not resolve in this repository: {exc}")


def render_candidates(repo_root: Path, rev: str, work_dir: Path) -> Any:
    """Render the candidate carriers from blob-materialized inputs and prove
    the result is byte-identical to what PR-P1b published.

    A mismatch means either the pinned inputs moved or the renderer changed —
    both invalidate the review subject, so this fails closed rather than
    publishing a silently re-anchored attestation.
    """
    probe = _probe_module()
    try:
        render = probe.build_candidate_render(repo_root, rev, work_dir)
    except probe.GitError as exc:
        # Shallow clones (ci.yml checks out depth 1) cannot reach the anchor;
        # that is an unusable input, not a crash.
        _die(f"cannot render at --rev {rev}: {exc}")
    if not render.deterministic:
        _die("candidate render is not deterministic on this tree")
    if render.manifest_violations:
        _die(f"candidate manifest violations: {render.manifest_violations}")

    fixture = json.loads(
        (repo_root / P1B_FIXTURE_RELPATH).read_text(encoding="utf-8")
    )
    if fixture["pinned_head"] != rev:
        _die(
            f"fixture is pinned at {fixture['pinned_head']} but --rev is {rev};"
            " the published candidate digests are the review subject and may"
            " not be re-anchored here"
        )
    published = fixture["candidate_output_sha256"]
    actual = {path: sha256_hex(data) for path, data in render.outputs.items()}
    if actual != published:
        drift = sorted(
            p for p in set(actual) | set(published)
            if actual.get(p) != published.get(p)
        )
        _die(
            "rendered candidate digests differ from the PR-P1b published set"
            f" on {len(drift)} path(s): {drift[:5]}"
        )
    return render


def translated_ids(render: Any) -> list[str]:
    return sorted(render.partition["translated"])


# ------------------------------------------------------------------ coverage


def build_coverage_reports(
    repo_root: Path, rev: str, render: Any
) -> dict[str, dict[str, Any]]:
    """One machine-generated coverage report per translated capability."""
    probe = _probe_module()
    from scripts.sdd._common import skill_renderer as sr

    registry = sr.load_workflow_registry(
        probe.git_blob_bytes(
            repo_root, rev, sr.WORKFLOW_REGISTRY_RELPATH
        ).decode("utf-8")
    )
    carrier_ids = set(render.partition["translated"]) | set(
        render.partition["byte-copy"]
    )
    reports: dict[str, dict[str, Any]] = {}
    for cap in translated_ids(render):
        source_bytes = probe.git_blob_bytes(
            repo_root, rev, f"{SOURCE_ROOT}/{cap}/SKILL.md"
        )
        artifact_bytes = render.outputs[f"{ARTIFACT_ROOT}/{cap}/SKILL.md"]
        reports[cap] = sr.generate_coverage(
            cap, source_bytes, artifact_bytes.decode("utf-8"), registry, carrier_ids
        )
    return reports


def coverage_drift(repo_root: Path, blobs: Mapping[str, bytes]) -> list[str]:
    """Capabilities whose committed report no longer matches a fresh render.

    Split out from `main` so the drift verdict is reachable without a Git
    history: `ci.yml` checks out shallow, and a test that could only run
    locally would leave this path unpinned.
    """
    drifted: list[str] = []
    for cap in sorted(blobs):
        target = repo_root / COVERAGE_RELDIR / f"{cap}.json"
        current = target.read_bytes() if target.is_file() else b""
        if current != blobs[cap]:
            drifted.append(cap)
    return drifted


def coverage_bytes(report: dict[str, Any]) -> bytes:
    """On-disk form of a coverage report: schema field order preserved for
    readability; the digest that matters (`inventory_sha256`) is computed over
    a sorted canonical projection inside the renderer, so it does not depend on
    this serialization."""
    return (
        json.dumps(report, ensure_ascii=False, indent=2) + "\n"
    ).encode("utf-8")


# --------------------------------------------------------------- set digests


def tranche_digests(
    repo_root: Path,
    rev: str,
    render: Any,
    capability_ids: tuple[str, ...],
    coverage_blobs: Mapping[str, bytes],
) -> dict[str, str]:
    """The eight §2.8.5 digest fields for one tranche.

    Tranche-scoped: source / artifact / coverage (the members under review).
    Whole-input: manifest / translation / workflow / preface / renderer — the
    same render inputs every tranche was reviewed against.
    """
    probe = _probe_module()
    from scripts.sdd._common import skill_renderer as sr

    def blob_sha(relpath: str) -> str:
        return sha256_hex(probe.git_blob_bytes(repo_root, rev, relpath))

    source_set = {
        f"{SOURCE_ROOT}/{cap}/SKILL.md": blob_sha(f"{SOURCE_ROOT}/{cap}/SKILL.md")
        for cap in capability_ids
    }
    artifact_set = {
        f"{ARTIFACT_ROOT}/{cap}/SKILL.md": sha256_hex(
            render.outputs[f"{ARTIFACT_ROOT}/{cap}/SKILL.md"]
        )
        for cap in capability_ids
    }
    coverage_set = {
        f"{COVERAGE_RELDIR}/{cap}.json": sha256_hex(coverage_blobs[cap])
        for cap in capability_ids
    }
    # det-12's seven pinned modules: the three declared-version renderers alone
    # let the orchestration layer drift self-consistently (PR-P1b Stage 11).
    # The MEMBERSHIP comes from `renderer_identity`, but the digests are
    # recomputed with the same raw-blob closure as every other set here —
    # `renderer_identity.blob_sha256` is LF-NORMALIZED, and §2.7 fixes the wire
    # as `path -> raw_sha256`. Both values coincide today (all seven blobs are
    # already LF), so this changes no published digest; it removes a latent
    # divergence rather than fixing a live one (Stage 11 finding).
    renderer_set = {
        info["relpath"]: blob_sha(info["relpath"])
        for info in render.renderer_identity.values()
    }
    return {
        "manifest_set_sha256": set_digest(
            {MANIFEST_RELPATH: blob_sha(MANIFEST_RELPATH)}
        ),
        "source_set_sha256": set_digest(source_set),
        "artifact_set_sha256": set_digest(artifact_set),
        "translation_set_sha256": set_digest(
            {sr.TRANSLATION_MAP_RELPATH: blob_sha(sr.TRANSLATION_MAP_RELPATH)}
        ),
        "workflow_set_sha256": set_digest(
            {sr.WORKFLOW_REGISTRY_RELPATH: blob_sha(sr.WORKFLOW_REGISTRY_RELPATH)}
        ),
        "preface_sha256": blob_sha(sr.PREFACE_RELPATH),
        "renderer_set_sha256": set_digest(renderer_set),
        "coverage_set_sha256": set_digest(coverage_set),
    }


# -------------------------------------------------------------------- packet


def build_packet(
    repo_root: Path,
    rev: str,
    render: Any,
    tranche_id: str,
    capability_ids: tuple[str, ...],
    reports: Mapping[str, dict[str, Any]],
    digests: Mapping[str, str],
) -> str:
    """Reviewer packet for one tranche.

    Carries exactly what plan §2.7 item 9 makes mandatory — the per-capability
    source-description -> discovery-summary trigger judgment — plus the digests
    the reviewer copies into their record, plus the finite set of TRANSFORMED
    items that constitutes the real body spot-check surface (items whose source
    and artifact digests match cannot have changed meaning, and that is
    verifiable from the tracked source alone).

    Candidate artifact BODIES are not reproduced here: PR-P1b published digests
    only, and §2.7 explicitly does not ask for an unaided full-text read. §3
    gives a scratch-directory recipe for reading one carrier's rendered text
    without touching anything tracked.
    """
    probe = _probe_module()
    lines: list[str] = []
    lines.append(f"# Reviewer packet — `{tranche_id}`")
    lines.append("")
    lines.append(
        f"> Epic #499 PR-C0 · plan §2.7 item 9 / §2.8.5 · candidate commit"
        f" `{rev}`"
    )
    lines.append("")
    lines.append("## 0. What you are being asked to judge")
    lines.append("")
    lines.append(
        "1. **Trigger judgment (mandatory, per capability)** — does the rendered"
        " `codex_discovery_summary` preserve the *triggering semantics* of the"
        " source `description`? It must not widen the trigger (Codex firing the"
        " skill where Claude would not) nor narrow it (the skill becoming"
        " undiscoverable)."
    )
    lines.append(
        "2. **Body fidelity spot-check (sampled, not exhaustive)** — §2.7 asks"
        " for `抽查`, explicitly *not* an unaided full-text read. The coverage"
        " report already proves structural closure; your sample is about"
        " meaning."
    )
    lines.append(
        "3. **Verdict** — `approved` or `rejected`. There is no pending value:"
        " if you have not actually performed the judgment, do not record one."
    )
    lines.append("")
    lines.append(
        "The author of this packet may not fill in your verdict. The digests in"
        " §2 *were* computed by the author's producer — so before copying them"
        " into your record, recompute them yourself with the command in §3 and"
        " confirm they are the values your review was actually performed"
        " against. The producer will refuse to emit an index whose record"
        " disagrees with the tree, but it cannot tell whether a record is"
        " genuinely yours; that part rests on you creating it."
    )
    lines.append("")
    lines.append("## 1. Trigger judgment material")
    lines.append("")
    for cap in capability_ids:
        source_bytes = probe.git_blob_bytes(
            repo_root, rev, f"{SOURCE_ROOT}/{cap}/SKILL.md"
        )
        artifact_bytes = render.outputs[f"{ARTIFACT_ROOT}/{cap}/SKILL.md"]
        source_desc = probe.frontmatter_description(source_bytes)
        summary = probe.frontmatter_description(artifact_bytes)
        # `frontmatter_description` returns None for anything it cannot parse
        # (a CRLF blob does exactly that). Defaulting to "" would publish an
        # EMPTY trigger judgment — the one thing §2.7 item 9 makes mandatory —
        # and still exit 0, so fail closed instead (Stage 11 finding).
        if not source_desc or not summary:
            _die(
                f"{cap}: cannot build the trigger-judgment material —"
                f" source description {'missing' if not source_desc else 'ok'},"
                f" rendered summary {'missing' if not summary else 'ok'}."
                " Publishing an empty judgment surface would defeat the packet."
            )
        report = reports[cap]
        kinds: dict[str, int] = {}
        for item in report["items"]:
            kinds[item["item_kind"]] = kinds.get(item["item_kind"], 0) + 1
        lines.append(f"### `{cap}`")
        lines.append("")
        lines.append(f"**Claude-side source `description`** ({len(source_desc)} chars)")
        lines.append("")
        lines.append("```text")
        lines.append(source_desc)
        lines.append("```")
        lines.append("")
        lines.append(
            f"**Codex-side rendered `codex_discovery_summary`**"
            f" ({len(summary)} chars, budget 1024)"
        )
        lines.append("")
        lines.append("```text")
        lines.append(summary)
        lines.append("```")
        lines.append("")
        # The spot-check surface is the DECLARED transforms. Digest inequality
        # alone is a bad proxy: `generate_coverage` digests the raw source line
        # but the stripped artifact slice, so an indented line differs in
        # digest while being verbatim in content.
        transformed = [
            i for i in report["items"] if i["transform_class"] != "NOOP"
        ]
        identical = [
            i for i in report["items"]
            if i["source_sha256"] == i["artifact_sha256"]
        ]
        whitespace = [
            i for i in report["items"]
            if i["transform_class"] == "NOOP"
            and i["source_sha256"] != i["artifact_sha256"]
            and i["item_kind"] != "frontmatter-description"
        ]
        lines.append(
            f"Coverage: **{len(report['items'])} items** — "
            + ", ".join(f"{k} {v}" for k, v in sorted(kinds.items()))
            + "."
        )
        lines.append("")
        lines.append(
            f"- **{len(identical)}** byte-identical between source and"
            " artifact (both digests equal) — these cannot have changed"
            " meaning, provable from the tracked source alone"
        )
        lines.append(
            f"- **{len(whitespace)}** identical apart from leading indentation"
            " (the report digests the raw source line against the stripped"
            " artifact slice)"
        )
        lines.append(
            "- **1** frontmatter description, replaced by the discovery"
            " summary — that is the §1 trigger judgment above"
        )
        lines.append(
            f"- **{len(transformed)}** carry a declared transform — **this is"
            " your body spot-check surface**"
        )
        lines.append("")
        if transformed:
            lines.append("| item | kind | transform | source locator |")
            lines.append("|---|---|---|---|")
            for item in transformed:
                lines.append(
                    f"| `{item['item_id']}` | {item['item_kind']} |"
                    f" `{item['transform_class']}` |"
                    f" `{item['source_locator']}` |"
                )
            lines.append("")
            lines.append(
                "`T2a` / `T2b` rewrite a cross-skill reference onto the Codex"
                " carrier path or an edge-route marker; they are the only"
                " places this translation can distort a routing instruction."
            )
            lines.append("")
        lines.append(
            f"- source blob `{report['source_sha256']}`"
        )
        lines.append(
            f"- candidate artifact `{report['artifact_sha256']}`"
        )
        lines.append(
            f"- coverage report [`{cap}.json`](../coverage/{cap}.json)"
            f" — `inventory_sha256` `{report['inventory_sha256']}`"
        )
        lines.append("")
    lines.append("## 2. Digests to copy into your record")
    lines.append("")
    lines.append("| field | value |")
    lines.append("|---|---|")
    lines.append(f"| `reviewed_candidate_commit_sha` | `{rev}` |")
    lines.append(
        f"| `reviewed_source_set_sha256` | `{digests['source_set_sha256']}` |"
    )
    lines.append(
        f"| `reviewed_artifact_set_sha256` | `{digests['artifact_set_sha256']}` |"
    )
    lines.append("")
    lines.append(
        "The producer refuses to emit the index unless these three values in"
        " your record equal the ones this tree computes, so a record reviewed"
        " against stale inputs cannot be silently upgraded."
    )
    lines.append("")
    lines.append("## 3. Recomputing the digests yourself")
    lines.append("")
    lines.append(
        "This regenerates the coverage reports from Git blob bytes at the"
        " pinned commit and compares them against what is committed. It writes"
        " nothing when it agrees (exit 0) and lists the drifted reports when it"
        " does not (exit 1):"
    )
    lines.append("")
    lines.append("```bash")
    lines.append(
        "uv run --frozen --no-sync python"
        " scripts/sdd/build_fidelity_attestations.py \\"
    )
    lines.append(f"    build-coverage --check --rev {rev}")
    lines.append("```")
    lines.append("")
    lines.append(
        "Candidate artifact bytes are deliberately not committed (PR-P1b Gate 1"
        " published digests only). To read the rendered text of one carrier —"
        " needed only if you want to inspect a transformed item above — render"
        " it into a scratch directory; this touches nothing tracked:"
    )
    lines.append("")
    lines.append("```bash")
    lines.append("uv run --frozen --no-sync python - <<'EOF'")
    lines.append("import tempfile, pathlib")
    lines.append("import scripts.sdd.build_fidelity_attestations as b")
    lines.append("cap = " + repr(capability_ids[0]))
    lines.append("with tempfile.TemporaryDirectory() as t:")
    lines.append(
        f"    r = b.render_candidates(pathlib.Path('.'), {rev!r},"
        " pathlib.Path(t))"
    )
    lines.append(
        "    print(r.outputs[f'.agents/skills/{cap}/SKILL.md']"
        ".decode('utf-8'))"
    )
    lines.append("EOF")
    lines.append("```")
    lines.append("")
    lines.append(
        "Do **not** run the probe's `emit-fixtures` mode for this: it writes"
        " into `evidence/development-agent-v8/probe/fixtures/` — a tracked"
        " artifact PR-P1b froze — and it emits digests, not carrier text."
    )
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------- index


def load_bindings(path: Path, tranche_ids: list[str]) -> dict[str, dict[str, Any]]:
    """Reviewer-supplied approval records. Every field arrives verbatim; this
    producer validates shape and never invents one."""
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        _die(f"bindings file unreadable: {exc}")
    if not isinstance(raw, list):
        _die("bindings file must be a JSON list of records")
    out: dict[str, dict[str, Any]] = {}
    seen_records: set[str] = set()
    for entry in raw:
        if not isinstance(entry, dict) or "tranche_id" not in entry:
            _die("each binding record needs a tranche_id")
        tid = str(entry["tranche_id"])
        if tid not in tranche_ids:
            _die(f"binding for unknown tranche_id {tid!r}")
        if tid in out:
            _die(f"duplicate binding for tranche {tid!r}")
        binding = {k: v for k, v in entry.items() if k != "tranche_id"}
        if set(binding) != BINDING_KEYS:
            _die(
                f"tranche {tid!r}: approval_binding keys not exact —"
                f" {sorted(set(binding) ^ BINDING_KEYS)}"
            )
        if binding["verdict"] not in VERDICTS:
            _die(
                f"tranche {tid!r}: verdict {binding['verdict']!r} invalid"
                " (approved|rejected — there is no pending value; an"
                " unperformed review is BLOCKED_PREREQUISITE, not a verdict)"
            )
        record_id = str(binding["immutable_record_id"])
        if record_id in seen_records:
            _die(
                f"immutable_record_id {record_id!r} reused — a re-review must"
                " create a NEW record, never mutate a merged one"
            )
        seen_records.add(record_id)
        out[tid] = binding
    missing = [t for t in tranche_ids if t not in out]
    if missing:
        _die(
            "BLOCKED_PREREQUISITE: no reviewer record for tranche(s)"
            f" {missing}. AC-10 requires an immutable APPROVED binding for all"
            " 13 translated carriers; the producer will not synthesize one."
        )
    return out


def build_index(
    render: Any,
    per_tranche: Mapping[str, dict[str, str]],
    bindings: Mapping[str, dict[str, Any]],
    rev: str,
) -> dict[str, Any]:
    caps = translated_ids(render)
    tranches: list[dict[str, Any]] = []
    for tranche_id, capability_ids in TRANCHES:
        digests = per_tranche[tranche_id]
        binding = bindings[tranche_id]
        for field, computed in (
            ("reviewed_candidate_commit_sha", rev),
            ("reviewed_source_set_sha256", digests["source_set_sha256"]),
            ("reviewed_artifact_set_sha256", digests["artifact_set_sha256"]),
        ):
            if binding[field] != computed:
                _die(
                    f"tranche {tranche_id!r}: the reviewer record's {field}"
                    f" ({binding[field]}) does not match what this tree"
                    f" computes ({computed}) — the review was performed"
                    " against different inputs and may not be rebound here"
                )
        tranches.append(
            {
                "tranche_id": tranche_id,
                "capability_ids": list(capability_ids),
                "candidate_commit_sha": rev,
                **digests,
                "approval_binding": dict(binding),
            }
        )
    return {
        "schema_version": INDEX_SCHEMA_VERSION,
        "translated_capabilities": caps,
        "coverage_reports": [f"{COVERAGE_RELDIR}/{cap}.json" for cap in caps],
        "tranches": tranches,
    }


# ---------------------------------------------------------------------- main


def _check_partition(caps: list[str]) -> None:
    declared: list[str] = []
    for _tid, members in TRANCHES:
        declared.extend(members)
    if sorted(declared) != sorted(set(declared)):
        _die("declared tranche partition overlaps")
    if sorted(declared) != sorted(caps):
        _die(
            "declared tranche partition does not cover the translated set"
            f" exactly: declared={sorted(declared)} translated={sorted(caps)}"
        )
    if not 3 <= len(TRANCHES) <= 4:
        _die("tranche count must be 3-4")


def _write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def main(argv: list[str] | None = None, repo_root: Path | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog=_SCRIPT_NAME,
        description="PR-C0 fidelity attestation producer (plan §2.7/§2.8.5)",
    )
    parser.add_argument(
        "mode", choices=("build-coverage", "build-packet", "build-index")
    )
    parser.add_argument("--repo-root", type=Path, default=None)
    parser.add_argument(
        "--rev", default=CANDIDATE_REV,
        help="candidate commit to render from (default: the PR-P1b anchor)",
    )
    parser.add_argument(
        "--bindings", type=Path, default=None,
        help="JSON list of reviewer-supplied approval records (build-index)",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="build-coverage only: recompute and compare against the tree"
             " instead of writing",
    )
    args = parser.parse_args(argv)

    # A flag documented as "instead of writing" must never write. `--check` is
    # implemented for build-coverage only, so refuse it elsewhere rather than
    # silently ignoring it and writing anyway (Stage 11 finding).
    if args.check and args.mode != "build-coverage":
        parser.error(
            f"--check is implemented for build-coverage only, not {args.mode};"
            " reviewer packets and the index are fully derived, so re-run the"
            " mode and inspect `git diff` to see drift"
        )

    root = args.repo_root or repo_root or _REPO_ROOT
    root = Path(root).resolve()
    rev = canonical_rev(root, args.rev)

    with tempfile.TemporaryDirectory(prefix="mj-c0-render-") as tmp:
        render = render_candidates(root, rev, Path(tmp))
        caps = translated_ids(render)
        _check_partition(caps)
        reports = build_coverage_reports(root, rev, render)
        blobs = {cap: coverage_bytes(reports[cap]) for cap in caps}

        if args.mode == "build-coverage":
            if args.check:
                drifted = coverage_drift(root, blobs)
                for cap in drifted:
                    print(f"[DRIFT] {COVERAGE_RELDIR}/{cap}.json")
                print(f"=== Summary === drifted reports: {len(drifted)}")
                # Drift is a violation, not an unusable input: the repo-wide
                # convention (agents_sync --check, task0_freeze --check) is
                # 0 clean / 1 drift / 2 fatal.
                return 1 if drifted else 0
            for cap in caps:
                _write(root / COVERAGE_RELDIR / f"{cap}.json", blobs[cap])
            total = sum(len(reports[c]["items"]) for c in caps)
            print(
                f"wrote {len(caps)} coverage reports ({total} items) @"
                f" {rev[:12]}"
            )
            return 0

        per_tranche = {
            tid: tranche_digests(root, rev, render, members, blobs)
            for tid, members in TRANCHES
        }

        if args.mode == "build-packet":
            for tranche_id, members in TRANCHES:
                text = build_packet(
                    root, rev, render, tranche_id, members, reports,
                    per_tranche[tranche_id],
                )
                _write(
                    root / PACKET_RELDIR / f"{tranche_id}.md",
                    text.encode("utf-8"),
                )
            print(f"wrote {len(TRANCHES)} reviewer packets @ {rev[:12]}")
            return 0

        if args.bindings is None:
            _die(
                "BLOCKED_PREREQUISITE: build-index requires --bindings with a"
                " real reviewer record per tranche. The verdict enum is"
                " approved|rejected with no pending value, so emitting an index"
                " without records would assert a review that did not happen"
                " (plan §1.4 / §2.7: the author may not fill a reviewer"
                " verdict)."
            )
        tranche_ids = [tid for tid, _ in TRANCHES]
        bindings = load_bindings(args.bindings, tranche_ids)
        index = build_index(render, per_tranche, bindings, rev)
        text = yaml.safe_dump(index, sort_keys=False, allow_unicode=True)
        _write(root / INDEX_RELPATH, text.encode("utf-8"))
        approved = sum(
            1 for t in index["tranches"]
            if t["approval_binding"]["verdict"] == "approved"
        )
        print(
            f"wrote {INDEX_RELPATH}: {len(index['tranches'])} tranches,"
            f" {approved} approved, {len(caps)} translated carriers"
        )
        if approved != len(index["tranches"]):
            # A `rejected` record is schema-legal and must stay writable (it is
            # the §5.7 rollback path), but the merge condition is "all 13
            # approved" — say so loudly rather than letting a written index
            # read as a finished one.
            rejected = [
                t["tranche_id"] for t in index["tranches"]
                if t["approval_binding"]["verdict"] != "approved"
            ]
            print(
                "AC-10 NOT MET: merge condition is all 13 translated carriers"
                f" approved; rejected/non-approved tranche(s): {rejected}"
            )
        return 0


if __name__ == "__main__":
    sys.exit(main())
