"""scripts/sdd/generate_archive_index.py — archive/INDEX.md generator (M5-PR0).

Mirrors scripts/sdd/generate_index.py: builds ``archive/INDEX.md`` content
from each archive unit's ``archive.yml`` (one table row per unit:
original_path / archived_at / reason / ai_visibility / retention_class /
superseded_by).

This PR (M5-PR0) wires the ``--check`` step in **WARNING mode only** (no
blocking flip — deferred to the M5 move PRs).

Modes:
- default (write): regenerate ``archive/INDEX.md`` from current archive.yml
  manifests and write the file.
- ``--check``: regenerate to memory; byte-compare to committed
  ``archive/INDEX.md``; WARN on drift (NOT fail unless ``--strict``).
- ``--dry-run``: count archive.yml manifests; no I/O.

No-op: if ``archive/`` does not exist, print a clean no-op line and return 0.
This PR does NOT create ``archive/`` or ``archive/INDEX.md`` — archive/ is
born in the M5 move PRs.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.sdd._common.cli import Severity, Summary, build_argparser  # noqa: E402
from scripts.sdd._common.discovery import resolve_display_path  # noqa: E402

_SCRIPT_NAME = "generate_archive_index"
_MANIFEST_NAME = "archive.yml"
_INDEX_NAME = "INDEX.md"

_INDEX_HEADER = """\
<!-- AUTO-GENERATED by scripts/sdd/generate_archive_index.py — DO NOT EDIT MANUALLY. -->
<!-- Source of truth: each archive unit's archive.yml. -->
<!-- Run `uv run python scripts/sdd/generate_archive_index.py` to regenerate. -->

# archive/ INDEX (auto-generated)

> Auto-generated catalog of archived units. Each row is compiled from an
> archive unit's `archive.yml`. AI visibility: `hidden` = AI should not read
> the archived content; `reference` = AI may cite for historical background.

| original_path | archived_at | reason | ai_visibility | retention_class | superseded_by |
|---|---|---|---|---|---|"""


def _cell(value: object) -> str:
    """Render a YAML value as a safe Markdown table cell."""
    if value is None:
        return ""
    if isinstance(value, list):
        return ", ".join(str(item).replace("|", "\\|") for item in value)
    return str(value).replace("|", "\\|").replace("\n", " ")


def _build_index_content(archive_dir: Path) -> str:
    """Compose the full archive/INDEX.md content from every archive.yml."""
    manifests = sorted(archive_dir.rglob(_MANIFEST_NAME))
    parts: list[str] = [_INDEX_HEADER]

    rows: list[str] = []
    for manifest_path in manifests:
        try:
            with manifest_path.open("r", encoding="utf-8") as handle:
                data = yaml.safe_load(handle)
        except (yaml.YAMLError, OSError):
            continue
        if not isinstance(data, dict):
            continue
        rows.append(
            "| "
            + " | ".join(
                (
                    _cell(data.get("original_path")),
                    _cell(data.get("archived_at")),
                    _cell(data.get("reason")),
                    _cell(data.get("ai_visibility")),
                    _cell(data.get("retention_class")),
                    _cell(data.get("superseded_by")),
                )
            )
            + " |"
        )

    if rows:
        parts.extend(rows)
    else:
        parts.append("| _(none)_ | | | | | |")

    parts.append("")
    return "\n".join(parts) + "\n"


def main(argv: list[str] | None = None, repo_root: Path | None = None) -> int:
    """archive/INDEX.md generator entry point. ``repo_root`` overridable for isolated tests."""
    parser = build_argparser(
        _SCRIPT_NAME,
        "Generate archive/INDEX.md from each archive unit's archive.yml. "
        "M5-PR0 gate-prep; --check is WARNING mode in CI (blocking flip deferred "
        "to M5 move PRs). Use --check to verify committed file matches regeneration.",
        _MANIFEST_NAME,
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate to memory; compare with committed archive/INDEX.md; WARN on drift",
    )
    args = parser.parse_args(argv)

    if repo_root is None:
        repo_root = Path(__file__).resolve().parent.parent.parent
    archive_dir = repo_root / "archive"

    if not archive_dir.exists():
        print(f"{_SCRIPT_NAME}: no archive/ yet (no-op; archive/INDEX.md born in M5 move PRs)")
        return 0

    manifests = sorted(archive_dir.rglob(_MANIFEST_NAME))

    if args.dry_run:
        print(
            f"{_SCRIPT_NAME}: {len(manifests)} archive.yml discovered; would "
            f"regenerate {resolve_display_path(archive_dir / _INDEX_NAME, repo_root)}"
        )
        return 0

    generated = _build_index_content(archive_dir)
    target = archive_dir / _INDEX_NAME

    if args.check:
        summary = Summary()
        if not target.exists():
            summary.add(
                Severity.WARN,
                f"{resolve_display_path(target, repo_root)} missing; run generator "
                "without --check to create it",
            )
        else:
            committed = target.read_text(encoding="utf-8")
            if committed != generated:
                summary.add(
                    Severity.WARN,
                    f"{resolve_display_path(target, repo_root)} drift detected "
                    "(committed bytes != regenerated). Re-run without --check to update.",
                )
            else:
                summary.add_aggregate_pass(
                    n=1,
                    message=(
                        f"{resolve_display_path(target, repo_root)} matches regenerated "
                        f"content ({len(manifests)} manifest(s))"
                    ),
                )
        summary.print_messages()
        print(
            f"{_SCRIPT_NAME}: "
            f"{summary.pass_count}P / {summary.warn_count}W / {summary.fail_count}F"
        )
        return summary.exit_code(strict=args.strict)

    # write mode
    target.write_text(generated, encoding="utf-8")
    print(
        f"{_SCRIPT_NAME}: generated {resolve_display_path(target, repo_root)} "
        f"({len(manifests)} manifest(s))"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
