"""scripts/sdd/generate_index.py — Phase M3 implementation.

Generates `capabilities/INDEX.auto.md` from each capability's `spec.yml`
plus cross-capability links from each `trace.yml`. Phase M0 skeleton
replaced under M3-FU-G1G2G9-IMPL. M3 warning mode; M4 strict.

Output is a separate file (`INDEX.auto.md`) from the manually-curated
`INDEX.md` so the rich human-authored content (Risk Inventory / Test
Coverage Snapshot / Next Phase narrative) stays untouched while G9
provides a mechanically-verifiable subset (Active Capabilities table +
Cross-Capability References).

Modes:
- default (write): regenerate `capabilities/INDEX.auto.md` from current
  `spec.yml` + `trace.yml`.
- `--check`: regenerate to memory; compare to committed `INDEX.auto.md`
  byte-for-byte; FAIL on drift (G9 idempotency).
- `--dry-run`: count spec.yml files; no I/O.

Sections generated:
- Active Capabilities table (id / name / domain / lifecycle / archive /
  last_verified / adapter_coverage).
- Cross-Capability References table (source / direction / target /
  surface / rationale), compiled from each trace.yml.
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.sdd._common import (  # noqa: E402
    Severity,
    Summary,
    build_argparser,
    load_contract,
    resolve_display_path,
)

_INDEX_AUTO_HEADER = """\
<!-- AUTO-GENERATED by scripts/sdd/generate_index.py — DO NOT EDIT MANUALLY. -->
<!-- Source of truth: each capability's spec.yml + trace.yml. -->
<!-- Run `uv run python scripts/sdd/generate_index.py` to regenerate. -->

# capabilities/ INDEX (auto-generated subset)

> G9 generated subset of the canonical `INDEX.md`. The manually-curated
> `INDEX.md` adds narrative sections (Risk Inventory / Test Coverage /
> Next Phase) that are not auto-derivable. M4+ may consolidate.

## Active Capabilities

| id | name | domain | lifecycle | archive | last_verified | adapter_coverage |
|---|---|---|---|---|---|---|"""


def _format_adapter_coverage(coverage: object) -> str:
    if isinstance(coverage, list):
        return ", ".join(str(s) for s in coverage)
    return ""


def _generate_active_capabilities(spec_files: list[Path], capabilities_dir: Path) -> list[str]:
    """Emit one Markdown table row per active spec.yml.

    Link path is relative to capabilities/INDEX.auto.md (the link target's
    location), so the format matches existing manual INDEX.md.
    """
    rows: list[str] = []
    for spec_path in spec_files:
        spec = load_contract(spec_path)
        if not isinstance(spec, dict):
            continue
        archive = spec.get("archive_state")
        if archive in ("archived", "purge-eligible"):
            continue
        spec_id = spec.get("id", "")
        name = spec.get("name", "")
        domain = spec.get("domain", "")
        lifecycle = spec.get("lifecycle_state", "")
        last_verified = spec.get("last_verified", "")
        coverage = _format_adapter_coverage(spec.get("adapter_coverage"))
        try:
            relpath = spec_path.resolve().relative_to(capabilities_dir.resolve())
            relpath_str = "./" + str(relpath).replace("\\", "/")
        except ValueError:
            relpath_str = str(spec_path)
        rows.append(
            f"| [{spec_id}]({relpath_str}) | {name} | {domain} | "
            f"{lifecycle} | {archive} | {last_verified} | {coverage} |"
        )
    return rows


def _generate_cross_capability_refs(trace_files: list[Path]) -> list[str]:
    """Emit one Markdown table row per cross_capability_refs[] entry."""
    rows: list[str] = []
    for trace_path in sorted(trace_files):
        trace = load_contract(trace_path)
        if not isinstance(trace, dict):
            continue
        source = trace.get("capability", "")
        cross_refs = trace.get("cross_capability_refs") or []
        if not isinstance(cross_refs, list):
            continue
        for ref in cross_refs:
            if not isinstance(ref, dict):
                continue
            direction = ref.get("direction", "")
            target = ref.get("target", "")
            surface = ref.get("surface", "").replace("|", "\\|")
            rationale = ref.get("rationale", "").replace("|", "\\|").replace("\n", " ")
            rows.append(
                f"| {source} | {direction} | {target} | `{surface}` | {rationale} |"
            )
    return rows


def _build_index_content(repo_root: Path) -> str:
    """Compose the full INDEX.auto.md content from spec.yml + trace.yml."""
    capabilities_dir = repo_root / "capabilities"
    spec_files = sorted(capabilities_dir.glob("*/*/spec.yml"))
    trace_files = sorted(capabilities_dir.glob("*/*/trace.yml"))

    parts: list[str] = [_INDEX_AUTO_HEADER]
    parts.extend(_generate_active_capabilities(spec_files, capabilities_dir))

    parts.append("")
    parts.append("## Cross-Capability References")
    parts.append("")
    parts.append("> Compiled from each capability's `trace.yml` `cross_capability_refs[]`.")
    parts.append("")
    parts.append("| Source | Direction | Target | Surface | Rationale |")
    parts.append("|---|---|---|---|---|")
    cross_rows = _generate_cross_capability_refs(trace_files)
    if cross_rows:
        parts.extend(cross_rows)
    else:
        parts.append("| _(none)_ | | | | |")

    parts.append("")
    return "\n".join(parts) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = build_argparser(
        script_name="generate_index.py",
        description=(
            "Generate capabilities/INDEX.auto.md from spec.yml + trace.yml (G9). "
            "Phase M3 warning mode; M4 strict. Use --check to verify committed "
            "file matches regeneration (idempotency)."
        ),
        contract_filename="spec.yml",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate to memory; compare with committed INDEX.auto.md; FAIL on drift",
    )
    args = parser.parse_args(argv)
    repo_root = Path.cwd()

    spec_files = sorted((repo_root / "capabilities").glob("*/*/spec.yml")) if (
        repo_root / "capabilities"
    ).exists() else []

    if args.dry_run:
        print(
            f"[dry-run] generate_index.py — Phase M3 impl; would walk {len(spec_files)} "
            f"spec.yml + corresponding trace.yml to regenerate capabilities/INDEX.auto.md"
        )
        return 0

    if not spec_files:
        print("no capabilities/*/spec.yml found")
        return 0

    summary = Summary()
    generated = _build_index_content(repo_root)
    target = repo_root / "capabilities" / "INDEX.auto.md"

    if args.check:
        if not target.exists():
            summary.add(
                Severity.WARN,
                "capabilities/INDEX.auto.md missing; run generator without --check to create it",
            )
        else:
            committed = target.read_text(encoding="utf-8")
            if committed != generated:
                summary.add(
                    Severity.WARN,
                    "capabilities/INDEX.auto.md drift detected (committed bytes != regenerated). "
                    "Re-run without --check to update.",
                )
            else:
                summary.add_aggregate_pass(
                    n=1,
                    message=f"capabilities/INDEX.auto.md matches regenerated content ({len(spec_files)} specs)",
                )
        summary.print_messages()
        print("\n=== Summary ===")
        print(f"PASS: {summary.pass_count} / WARN: {summary.warn_count} / FAIL: {summary.fail_count}")
        return summary.exit_code(strict=args.strict)

    # write mode
    target.write_text(generated, encoding="utf-8")
    print(f"generated {resolve_display_path(target, repo_root)} ({len(spec_files)} specs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
