"""codex_config_renderer.py — the `.codex/config.toml` output-class renderer.

This is the `codex_config_renderer` module pre-registered in
`policies/ai-agent.md` §4 (A14 row (b), D-017 extended adjacency; ADR-039 —
PR-B/D/E surfaces enrolled ahead of landing). Extracted VERBATIM from
`scripts/sdd/agents_sync.py` (emitter B, dual-agent-compat v5 S2 #330) at Epic
#499 PR-B so the config output class has its own focused renderer module and
version: the v2 lock records `renderer_module` / `renderer_module_sha256` /
`renderer_version` per output class, and a README/skill renderer change must
not churn the config entry (plan §2.6). The v1 real-tree output is
byte-identical to the pre-extraction emitter — proven by the V11 drift gate
and a pinned real-tree test.

Direct route only (Gate 1 拍板, PR-B): the emitter input model stays the fixed
posture triple + `mcp_servers` subtree — the composite/explicit-route
`_POSTURE_KEYS` extension is deliberately NOT implemented here; it belongs to
PR-D1a behind its own D-017 approval if the explicit route is ever chosen.

Read-only inputs; no secrets (env values are projected BY NAME only); ASCII
output; LF; deterministic.
"""

from __future__ import annotations

import json
import re
from typing import Any

RENDERER_MODULE = "scripts.sdd._common.codex_config_renderer"
RENDERER_VERSION = 1

# Source `.mcp.json` server fields the emitter understands; anything else is an
# Owner decision, not a silent projection.
ALLOWED_SERVER_FIELDS = {"type", "command", "args", "env"}
# Pure by-name reference form — the ONLY env value shape that may be projected
# (becomes an `env_vars` whitelist entry; `${VAR:-default}` carries literals, refuse).
ENV_REF = re.compile(r"^\$\{([A-Za-z_][A-Za-z0-9_]*)\}$")
# args are projected verbatim, so they must carry NO substitution syntax at all:
# Codex does not interpolate `${VAR}` (a pure ref silently breaks the server) and
# `${VAR:-default}` defaults embed literals (e.g. credential URLs) — both refuse.
ARG_USERINFO = re.compile(r"://[^/\s:@]+:[^@\s]+@")
# Arg-pair rewrite (manifest serena `transform` note): Codex consumes its own context.
CONTEXT_ARG = "--context"
CONTEXT_TRANSFORM = {"claude-code": "codex"}
POSTURE_KEYS = ("approval_policy", "sandbox_mode", "project_doc_max_bytes")

CODEX_CONFIG_HEADER = """\
# GENERATED -- do not edit this file. Owned 100% by scripts/sdd/agents_sync.py
# (emitter B; dual-agent-compat v5 S2 #330, ADR-036 D-011/D-012).
# Derived from .mcp.json (A14 hard-stop source, human-maintained) filtered by the
# manifest `mcp` per-server tiers (D-013) + `codex.posture` (D-017) in
# sdd/development-agent.yml. Secrets are referenced BY NAME via `env_vars`
# (Codex TOML has no ${VAR} interpolation; Codex sanitizes MCP child env and
# `env_vars` inherits the named variables from the parent environment) --
# literal credentials must never appear here (G7 scans this file; V11 blocks drift).
# To change: edit the SOURCE through its own gate, then run
# `python scripts/sdd/agents_sync.py sync` and commit config + .agents.lock.json.
"""


class ConfigRenderError(ValueError):
    """Fail-closed render refusal — the caller must write nothing."""


def toml_str(value: str) -> str:
    # JSON string escaping is a valid TOML basic-string subset for our charset
    # (both escape backslash/quote the same way; \\uXXXX is valid TOML).
    return json.dumps(value, ensure_ascii=True)


def transform_args(args: list[str]) -> list[str]:
    out = list(args)
    for i, arg in enumerate(out[:-1]):
        if arg == CONTEXT_ARG and out[i + 1] in CONTEXT_TRANSFORM:
            out[i + 1] = CONTEXT_TRANSFORM[out[i + 1]]
    return out


def render_codex_config(
    mcp_project: dict[str, dict[str, Any]],
    posture: dict[str, Any] | None,
    mcp_json_servers: dict[str, Any],
) -> str:
    """Render `.codex/config.toml` text (LF, ASCII, deterministic). Fail-closed on
    anything the emitter does not positively understand."""
    if not isinstance(posture, dict):
        raise ConfigRenderError(
            "manifest codex.posture section required to render .codex/config.toml"
        )
    lines = CODEX_CONFIG_HEADER.rstrip("\n").split("\n")
    lines.append("")
    for key in POSTURE_KEYS:
        value = posture.get(key)
        if isinstance(value, bool) or value is None:
            raise ConfigRenderError(f"codex.posture.{key} missing or invalid")
        if isinstance(value, int):
            lines.append(f"{key} = {value}")
        elif isinstance(value, str):
            lines.append(f"{key} = {toml_str(value)}")
        else:
            raise ConfigRenderError(f"codex.posture.{key} must be a string or integer")

    for name in sorted(mcp_project):
        if not re.fullmatch(r"[A-Za-z0-9_-]+", name):
            raise ConfigRenderError(f"mcp server name {name!r} is not a bare TOML key")
        defn = mcp_json_servers.get(name)
        if not isinstance(defn, dict):
            raise ConfigRenderError(
                f"project-tier mcp server '{name}' missing from .mcp.json"
            )
        unknown = sorted(set(defn) - ALLOWED_SERVER_FIELDS)
        if unknown:
            raise ConfigRenderError(
                f"server '{name}' has field(s) the emitter does not understand:"
                f" {', '.join(unknown)} (fail-closed; needs an Owner decision)"
            )
        if defn.get("type", "stdio") != "stdio":
            raise ConfigRenderError(
                f"server '{name}' has type {defn.get('type')!r} — only stdio servers"
                " are projectable (fail-closed; needs an Owner decision)"
            )
        command = defn.get("command")
        if not isinstance(command, str) or not command:
            raise ConfigRenderError(f"server '{name}' needs a non-empty string 'command'")
        args = defn.get("args", [])
        if not isinstance(args, list) or not all(isinstance(a, str) for a in args):
            raise ConfigRenderError(f"server '{name}' 'args' must be a list of strings")
        for arg in args:
            if "${" in arg:
                raise ConfigRenderError(
                    f"server '{name}' has a substitution expression in args — Codex"
                    " does not interpolate ${VAR} (and ${VAR:-default} embeds"
                    " literals); args must be projectable verbatim (fail-closed)"
                )
            if ARG_USERINFO.search(arg):
                raise ConfigRenderError(
                    f"server '{name}' has a URL userinfo credential shape in args"
                    " — literal credentials are never projected (fail-closed)"
                )
        env = defn.get("env", {})
        if not isinstance(env, dict):
            raise ConfigRenderError(f"server '{name}' 'env' must be a mapping")
        env_names: list[str] = []
        for env_key in sorted(env):
            env_val = env[env_key]
            match = ENV_REF.match(env_val) if isinstance(env_val, str) else None
            if match is None:
                raise ConfigRenderError(
                    f"server '{name}' env '{env_key}' is not a pure ${{VAR}} reference"
                    " -- literal values are never projected (fail-closed; secrets go"
                    " by NAME via env_vars)"
                )
            env_names.append(match.group(1))
        # The context rewrite is gated on the manifest per-server `transform` field
        # (D-013 SoT) — servers without it are projected with untouched args.
        if mcp_project[name].get("transform"):
            args = transform_args(args)
        lines.append("")
        lines.append(f"[mcp_servers.{name}]")
        lines.append(f"command = {toml_str(command)}")
        rendered_args = ", ".join(toml_str(a) for a in args)
        lines.append(f"args = [{rendered_args}]")
        if env_names:
            rendered_env = ", ".join(toml_str(n) for n in sorted(set(env_names)))
            lines.append(f"env_vars = [{rendered_env}]")
    return "\n".join(lines) + "\n"
